# roles/docker-compose-zerotier/tasks/main.yaml
---

- name: Create zigbee2mqtt dir
  file:
    path: "{{ data_dir }}/{{item}}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: docker
    mode: ug+rw,g+s
  loop:
   - zigbee2mqtt
   - zigbee2mqtt/data

- name: Generate default configuration.yaml
  template:
    src: configuration.yaml.j2
    dest: "{{ data_dir }}/zigbee2mqtt/data/configuration.yaml"
    owner: "{{ ansible_ssh_user }}"
    group: docker
    mode: ug+rw
    force: no
- name: Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ data_dir }}/zigbee2mqtt/docker-compose.yml"
    owner: "{{ ansible_ssh_user }}"
    group: docker
    mode: ug+rw
    force: no
- name: Deploy zigbee2mqtt
  docker_compose:
    project_src: "{{ data_dir }}/zigbee2mqtt"