timezone: Europe/Helsinki
letsencrypt_email: yourname@example.com
duckdns:
  token: abcdefg-asdf-qwerty-asdf
  domain: somethingexample.duckdns.org
zerotier:
  token: zerotiertoken
  network_id: zerotiernetworkid
data_dir: "/opt/smarthome"
installation_type: new
components:
  mosquitto: true
  zerotier: false
  zigbee2mqtt: true
  esphome: true
  codeserver: true
  btmqttgateway: false
  pihole: true
  frigate: true
  homebridge: false
  nodered: false

zigbee2mqtt:
  serial_port: tcp://192.168.20.31:23 # /dev/ttyUSB0 or tcp://ip:port
  device_type: network # serial or network
codeserver:
  password: editorsalasana
postgresql_databases:
- name: home-assistant
postgresql_users:
- name: home-assistant
  password: postgresqltietokantasalasana
frigate:
  image: blakeblackshear/frigate:stable-amd64
  edgetpu: pci # pci or usb or none
borg:
  encryption_passphrase: something-here-long-string
  repository: abcdefg@abcdefg.repo.borgbase.com:repo
  host: abcdefg.repo.borgbase.com
  bb_repo_name: avoin-alykoti
  bb_token: "not-in-use-yet"
  bb_region: eu
  bb_quota: true
  bb_quota_size: 5000