# roles/docker-compose-zerotier/tasks/main.yaml
---

- name: Create pi-hole dirs
  file:
    path: "{{ data_dir }}/{{item}}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: docker
    mode: ug+rw,g+s
  loop:
   - pi-hole
   - pi-hole/etc
   - pi-hole/etc/pihole
   - pi-hole/etc/dnsmasq.d
- name: Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ data_dir }}/pi-hole/docker-compose.yml"
    owner: "{{ ansible_ssh_user }}"
    group: docker
    mode: ug+rw
    force: no
- name: Deploy pi-hole
  docker_compose:
    project_src: "{{ data_dir }}/pi-hole"

- name: Wait until pi-hole has started and created dnsmasq.d configuration file
  wait_for:
    path: "{{ data_dir }}/pi-hole/etc/dnsmasq.d/01-pihole.conf"

- name: Create dnsmasq conf to make duckdns domain work without connection to external dns
  copy:
    content: "address=/{{duckdns.domain}}/{{ ansible_default_ipv4.address }}"
    dest: "{{ data_dir }}/pi-hole/etc/dnsmasq.d/99-smarthome.conf"
    force: no
    owner: "{{ ansible_ssh_user }}"
    group: docker
    mode: ug+rw
