# roles/docker-compose-zerotier/tasks/main.yaml
---

- name: Create pi-hole dirs
  file:
    path: "{{ data_dir }}/{{item}}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: docker
    mode: ug+rw,g+s
  loop:
   - pi-hole
   - pi-hole/etc
   - pi-hole/etc/pihole
   - pi-hole/etc/dnsmasq.d
- name: Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ data_dir }}/pi-hole/docker-compose.yml"
    owner: "{{ ansible_ssh_user }}"
    group: docker
    mode: ug+rw
    force: no
- name: Deploy pi-hole
  docker_compose:
    project_src: "{{ data_dir }}/pi-hole"