http:
  routers:
    httpsRedirect:
      entryPoints:
        - web
      rule: PathPrefix(`/`)
      middlewares:
        - httpsRedirect
      service: httpsRedirect
      priority: 1
    homeassistant:
      rule: "Host(`{{ duckdns.domain }}`)"
      service: homeassistant
      entrypoints:
        - websecure
      tls:
        certResolver: "duckdnsresolver"
        domains:
          - main: "*.{{ duckdns.domain }}"
          - sans: "{{duckdns.domain}}"
    codeserver:
      rule: "Host(`editor.{{ duckdns.domain }}`)"
      service: codeserver
      entrypoints:
        - websecure
      tls:
        certResolver: "duckdnsresolver"
        domains:
          - main: "*.{{ duckdns.domain }}"
          - sans: "{{duckdns.domain}}"

    frigate:
      rule: "Host(`frigate.{{ duckdns.domain }}`)"
      service: frigate
      entrypoints:
        - websecure
      tls:
        certResolver: "duckdnsresolver"
        domains:
          - main: "*.{{ duckdns.domain }}"
          - sans: "{{duckdns.domain}}"
    traefik:
      rule: "Host(`traefik.{{ duckdns.domain }}`)"
      service: traefik
      entrypoints:
        - websecure
      tls:
        certResolver: "duckdnsresolver"
        domains:
          - main: "*.{{ duckdns.domain }}"
          - sans: "{{duckdns.domain}}"
    pihole:
      rule: "Host(`pihole.{{ duckdns.domain }}`)"
      service: pihole
      entrypoints:
        - websecure
      tls:
        certResolver: "duckdnsresolver"
        domains:
          - main: "*.{{ duckdns.domain }}"
          - sans: "{{duckdns.domain}}"
    nodered:
      rule: "Host(`nodered.{{ duckdns.domain }}`)"
      service: homebridge
      entrypoints:
        - websecure
      tls:
        certResolver: "duckdnsresolver"
        domains:
          - main: "*.{{ duckdns.domain }}"
          - sans: "{{duckdns.domain}}"
    wireguard-ui:
      rule: "Host(`wireguard-ui.{{ duckdns.domain }}`)"
      service: wireguard-ui
      entrypoints:
        - websecure
      tls:
        certResolver: "duckdnsresolver"
        domains:
          - main: "*.{{ duckdns.domain }}"
          - sans: "{{duckdns.domain}}"

  services:
    httpsRedirect:
      loadBalancer:
        servers:
          - url: "http://localhost/"
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://{{ ansible_default_ipv4.address }}:8123"
    codeserver:
      loadBalancer:
        servers:
          - url: "http://{{ ansible_default_ipv4.address }}:8443"
    frigate:
      loadBalancer:
        servers:
          - url: "http://{{ ansible_default_ipv4.address }}:5000"
    traefik:
      loadBalancer:
        servers:
          - url: "http://{{ ansible_default_ipv4.address }}:8080" 
    pihole:
      loadBalancer:
        servers:
          - url: "http://{{ ansible_default_ipv4.address }}:9100"
    wireguard-ui:
      loadBalancer:
        servers:
          - url: "http://{{ ansible_default_ipv4.address }}:8088"


  middlewares:
    httpsRedirect:
      RedirectScheme:
        scheme: https
        permanent: true
