log:
  level: DEBUG

defaultEntryPoints:
  - websecure
  - web

logLevel: ERROR

api:
  insecure: true
  dashboard: true
  
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  file:
    filename: /etc/traefik/traefik-dyn.yml

certificatesResolvers:
  duckdnsresolver:
    acme:
      email: '{{ letsencrypt_email }}'
      storage: acme.json
      dnsChallenge:
        provider: duckdns