# Playbook inspired by https://github.com/vicchi/ansible-pi-lockdown (MIT license)

- name: Set static IP
  hosts: rpi
  become: yes

  vars_prompt:
    - name: "interface"
      prompt: "Ethernet interface"
      default: "eth0"
      private: no
    - name: "ipaddress"
      prompt: "Static IPv4 address"
      private: no
    - name: "routers"
      prompt: "Gateway"
      private: no
    - name: "dns_servers"
      prompt: "DNS servers (space separated)"
      default: "1.1.1.1 8.8.8.8"
      private: no
  
  tasks:
    - name: Configure static IP in  /etc/dhcpcd.conf
      become: yes
      lineinfile:
        dest:  /etc/dhcpcd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: "^interface eth[0-9]$", line: "interface {{ interface }}" }
        - { regexp: "^static ip_address", line: "static ip_address={{ ipaddress }}" }
        - { regexp: "^static routers", line: "static routers={{ routers }}" }
        - { regexp: "^static domain_name_servers", line: "static domain_name_servers={{ dns_servers }}" }
    - name: reboot
      command: shutdown -r +0 'Ansible Reboot triggered'
      async: 0
      poll: 0
      ignore_errors: true
      become: true

    - name: wait for reboot to finish
      local_action: wait_for host={{ ipaddress }} state=started port=22 delay=50 timeout=120
      become: false